<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net40</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
    <LangVersion>latest</LangVersion>
    <AssemblyName>ServicioTecnico.Tests</AssemblyName>
    <RootNamespace>ServicioTecnico.Tests</RootNamespace>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\ServicioTecnico.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Data.SQLite">
      <HintPath>..\..\Lib\System.Data.SQLite.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="BarcodeLib">
      <HintPath>..\..\Lib\BarcodeLib.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Data" />
  </ItemGroup>
</Project>
